# Path to the local samples
dir: '/eos/home-e/egovorko/'
background: '../../cernbox/cocktail_0.66invfb_fixed.h5'
leptoquarks: '../../cernbox/leptoquark_LOWMASS_lepFilter_13TeV_filtered.h5'
ato4l: '../../cernbox/Ato4l_lepFilter_13TeV_filtered.h5'
hChToTauNu: '../../cernbox/hChToTauNu_13TeV_PU20_filtered.h5'
hToTauTau: '../../cernbox/hToTauTau_13TeV_PU20_filtered.h5'
monojet: '../../cernbox/sig_fake_monojet_fixed.h5'

# Datasets constructed from samples above
datasets_dir: '/eos/cms/store/cmst3/user/egovorko/kd_output/'

# Graph results from Nadya
signal: '/eos/user/n/nchernya/MLHEP/AnomalyDetection/autoencoder_for_anomaly/graph_AD_event_based/run_19/evaluated/signals_evaluated_model21_merged_new.h5'
train: '/eos/user/n/nchernya/MLHEP/AnomalyDetection/autoencoder_for_anomaly/graph_AD_event_based/run_19/evaluated/background_train_fixed_evaluated_model21_merged.h5'
test: '/eos/user/n/nchernya/MLHEP/AnomalyDetection/autoencoder_for_anomaly/graph_AD_event_based/run_19/evaluated/background_validation_fixed_evaluated_model21_merged.h5'

# CNN teacher model
json: '/eos/cms/store/cmst3/user/egovorko/paper_output/model-conv_ae-8-b0-q4-pruned.json'
h5: '/eos/cms/store/cmst3/user/egovorko/paper_output/model-conv_ae-8-b0-q4-pruned.h5'

# Big Teacher AE with around 75k parameters
big_teacher_h5: '../../cernbox/big_teacher.h5'